### ISSUE TITLE
APScheduler v3.1.0 breaks mommy implementation

### ISSUE THREAD

**Issue by sklirg** [dotKom/onlineweb4#1560]
```
Traceback (most recent call last):
  File "/srv/www/onlineweb4/onlineweb4/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/www/onlineweb4/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/srv/www/onlineweb4/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/www/onlineweb4/env/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/www/onlineweb4/env/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/srv/www/onlineweb4/env/lib/python3.4/site-packages/django/core/management/base.py", line 584, in handle
    return self.handle_noargs(**options)
  File "/srv/www/onlineweb4/onlineweb4/apps/mommy/management/commands/mommy.py", line 10, in handle_noargs
    mommy.run()
  File "/srv/www/onlineweb4/onlineweb4/apps/mommy/__init__.py", line 35, in run
    from apscheduler.schedulers.blocking import BlockingScheduler
  File "/srv/www/onlineweb4/env/lib/python3.4/site-packages/apscheduler/__init__.py", line 3, in <module>
    version_info = tuple(int(x) if x.isdigit() else x for x in parsed_version.public.split('.'))
AttributeError: 'tuple' object has no attribute 'public'
2016-04-29 12:20:53,265 WARNING py.warnings:22 /srv/www/onlineweb4/env/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

```

**Comment by myth** [comment]
Thanks doppins :D

**Comment by sklirg** [comment]
I'm sure we want up to date requirements, so this would've happened sooner or later anyways.

**Comment by sklirg** [comment]
https://stackoverflow.com/questions/36437702/advance-python-scheduler-tuple-object-has-no-attribute-public-while-starting
