### ISSUE TITLE
Using html id-linking on frontpage gives TypeError

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb4#2244]
E.g. going to https://online.ntnu.no/#bedrifter gives a TypeError, in any browser (100% replicable)

Problem lies in 
https://github.com/dotkom/onlineweb4/blob/d954a020b1fc7aaabac81c31384d78b2b095ad80/assets/frontpage/initFrontpage.js#L82

https://sentry.io/organizations/dotkom/issues/355401966/?project=204971&referrer=github_plugin

```
TypeError: Cannot read property 'top' of undefined
  at None (./assets/frontpage/initFrontpage.js:82:72)
  at dispatch (/jquery-2.2.4.min.js:3:7537)
  at r.handle (/jquery-2.2.4.min.js:3:5620)
```

**Comment by henrikhorluck** [comment]
Fixed with #2251
