### ISSUE TITLE
`ui.element` is undefined in Safari on iOS in the Wiki

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb4#2250]
https://sentry.io/organizations/dotkom/issues/1005777181/?project=204971&referrer=github_plugin

```
TypeError: undefined is not an object (evaluating 'ui.element')
  at None (/wiki/online/info/trivia/folk/sekkemannen/_history/:615:9)
  at dispatch (/static/wiki/js/jquery.min.js:3:12449)
  at handle (/static/wiki/js/jquery.min.js:3:9178)
```

**Comment by henrikhorluck** [comment]
A related, but perhaps not the same issue
Sentry issue: [ONLINEWEB-4-TY](https://sentry.io/organizations/dotkom/issues/1005787062/?project=204971&referrer=github_plugin)

**Comment by henrikhorluck** [comment]
This is an error in Django-Wiki, I have opened an issue over there as well https://github.com/django-wiki/django-wiki/issues/952

**Comment by henrikhorluck** [comment]
Publicly viewable sentry links: https://sentry.io/share/issue/92701e0860924507bff46f8bfc9bc2f8/, https://sentry.io/share/issue/e91ec5523d17451cb51d543e1a33ccb9/

**Comment by henrikhorluck** [comment]
Sentry issue: [ONLINEWEB-4-WT](https://sentry.io/organizations/dotkom/issues/1154549379/?referrer=github_plugin)
