### ISSUE TITLE
TypeError: t is undefined in Dashboard image module

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb4#2295]
https://sentry.io/organizations/dotkom/issues/894784938/?referrer=github_plugin

```
TypeError: t is undefined
  at imagesObject (./assets/dashboard/core/Gallery.js:79:23)
  at i (/jquery-2.2.4.min.js:2:27151)
  at fireWith (/jquery-2.2.4.min.js:2:27914)
  at z (/jquery-2.2.4.min.js:4:12059)
  at c/< (/jquery-2.2.4.min.js:4:15619)
...
(1 additional frame(s) were not displayed)
```

**Comment by henrikhorluck** [comment]
Possibly related

Sentry issue: [ONLINEWEB-4-5H](https://sentry.io/organizations/dotkom/issues/355447109/?referrer=github_plugin)
