### ISSUE TITLE
jQuery throws an error when setting up event payment

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb4#2298]
https://sentry.io/organizations/dotkom/issues/1139373884/?referrer=github_plugin

```
TypeError: Cannot read property 'length' of undefined
  at Object.success (/static/js/payment.js:69:46)
  at i (/static/js/libs/jquery-2.2.4.min.js:2:27151)
  at Object.fireWith [as resolveWith] (/static/js/libs/jquery-2.2.4.min.js:2:27914)
  at z (/static/js/libs/jquery-2.2.4.min.js:4:12059)
  at XMLHttpRequest.<anonymous> (/static/js/libs/jquery-2.2.4.min.js:4:15619)
...
(1 additional frame(s) were not displayed)
```

**Comment by oleast** [comment]
Irrelevant since #2323
