### ISSUE TITLE
Patch OIDC-client errors on response-type

### ISSUE THREAD

**Issue by FluidSense** [dotkom/onlineweb4#2578]
**Describe the bug**
```
 2021-03-07 20:06:04,016 [ERROR] django.request: Internal Server Error: /api/v1/oidc/clients/9/
django_1   | Traceback (most recent call last):
django_1   |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
django_1   |     response = get_response(request)
django_1   |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
django_1   |     response = self.process_exception_by_middleware(e, request)
django_1   |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
django_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_1   |   File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/django/views.py", line 52, in callback
django_1   |     return old_callback(*args, **kwargs)
django_1   |   File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/django/views.py", line 52, in callback
django_1   |     return old_callback(*args, **kwargs)
django_1   |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
django_1   |     return view_func(*args, **kwargs)
django_1   |   File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 125, in view
django_1   |     return self.dispatch(request, *args, **kwargs)
django_1   |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
django_1   |     response = self.handle_exception(exc)
django_1   |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
django_1   |     self.raise_uncaught_exception(exc)
django_1   |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
django_1   |     raise exc
django_1   |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
django_1   |     response = handler(request, *args, **kwargs)
django_1   |   File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 82, in partial_update
django_1   |     return self.update(request, *args, **kwargs)
django_1   |   File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 68, in update
django_1   |     self.perform_update(serializer)
django_1   |   File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 78, in perform_update
django_1   |     serializer.save()
django_1   |   File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 200, in save
django_1   |     self.instance = self.update(self.instance, validated_data)
django_1   |   File "/srv/app/apps/online_oidc_provider/serializers.py", line 113, in update
django_1   |     setattr(instance, key, value)
django_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 546, in __set__
django_1   |     % self._get_set_deprecation_msg_params(),
django_1   | TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use response_types.set() instead.
django_1   | [07/Mar/2021 20:06:04] "PATCH /api/v1/oidc/clients/9/ HTTP/1.1" 500 24916
```

**To Reproduce**
Post a Patch-request with a new response-type. Get error.

**Expected behavior**
Expected OW4 to set new response type.

**Comment by FluidSense** [comment]
#2576 Will make this obsolete upon finishing
